### ISSUE TITLE
Location and process for submitting community-made models

### ISSUE THREAD

**Issue by aj-stein-gsa** [metaschema-framework/metaschema#20]
# User Story:

As a Metaschema enthusiast, I would like to know of a location and process to submit community made and maintained modules.

The recent inclusion of [the SARIF model into the core Metaschema code base](https://github.com/metaschema-framework/metaschema/commit/894b2238764c8732623a3894f0c236625ca5a686) inspired this request to include information models, for cybersecurity or other domains for use in heterogenous cross-domain information and data processing.

## Goals:

- [ ] Allow community members to submit Metaschema modules for feedback, potential inclusion, and maintenance by the community
- [ ] Centralize published efforts on cross-domain heterogenous information model analysis

## Dependencies:

None explicit ones at this time, I presume maintainers need to discuss this, and add information about a process to request review and inclusion with inline contributions in GitHub or creating a dedicated repository to open them. I am flexible as long as we provide an avenue for it.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by aj-stein-gsa** [comment]
@david-waltermire, for your review and consideration per ongoing discussions of this idea.

**Comment by david-waltermire** [comment]
This is addressed by the [new module repo](https://github.com/metaschema-framework/metaschema-modules).

**Comment by aj-stein-gsa** [comment]
So we don't want or need guidelines for review and inclusion? I can add that when I have time but we are basically asking for others to get review from us and we have not been clear on what/how/why you get our feedback and acceptance for a new model if community members come to us.
