### ISSUE TITLE
Add `DEBUG` level for constraints

### ISSUE THREAD

**Issue by aj-stein-gsa** [metaschema-framework/metaschema#33]
# User Story:

As a developer of Metaschema-enabled, I want the ability to define constraints with a `DEBUG` level and have guidance in a specification about how the data for violated constraints with this level can be omitted or ignored, so that I can make the debugging process for constraint development more straightforward.

I purposefully do not want constraints that trigger `message` output that is only meant for ad-hoc testing for development and for release.

## Goals:

- [ ] Make ad-hoc debugging of constraints faster; and
- [ ] Make them shareable amongst developers in constraints before, during, and after release of finalized constraint sets; while
- [ ] Not impacting noisy output from the released constraints whose outputs are only intended for downstream stakeholders via their outputs when violated

## Dependencies:

{Describe any previous issues or related work that must be completed to start or complete this issue.}

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

{The items above are general acceptance criteria for all User Stories. Please describe anything else that must be completed for this issue to be considered resolved.}

**Comment by david-waltermire** [comment]
There is already a [`DEBUG` level](https://github.com/metaschema-framework/metaschema/blob/7c03ce5844e46cf9d047193a37e44422ae6a7d61/schema/metaschema/metaschema-module-metaschema.xml#L1018). The specification [documents this](https://pages.nist.gov/metaschema/specification/syntax/constraints/#level).

For excluding levels, we might want to think about how to generalize this to exclude levels at a specific level or lower.

It's not clear how to address "Make them shareable amongst developers in constraints before, during, and after release of finalized constraint sets; while". 

@aj-stein-gsa any additional thoughts?

**Comment by aj-stein-gsa** [comment]
I am sorry I did not realize we wrapped this long ago enough that it rolled over into the fork. Apologies, I did not read the documentation and presumed. I am closing this out.

(NOTE: not sure what we do with this info and can toggle it on or off in metaschema-java, but that is another issue entirely.)
